"""
Module: main.py

The primary entry point for the Clinical RAG Assistant API — a FastAPI
app that orchestrates the full request flow: retrieval.py (SQL + vector
context) -> llm.py (Phi-3 answer generation) -> evaluation.py (live
safety/quality checks) -> structured JSON response.

Endpoints:
    POST /query    Submit a clinical question for a given MRD number.
                    Requires X-API-Key header. Rate-limited per IP.
    GET  /health   Multi-component health probe (LLM + retrieval).
    GET  /metrics  Runtime telemetry (query counts, latency, errors).
                    Requires X-API-Key header.
    GET  /docs     Interactive Swagger UI (auto-generated by FastAPI).

Run directly with `python main.py`, or via `uvicorn main:app --reload`
for auto-reload during development. Set CLINICAL_RAG_API_KEY in the
environment before starting — see "API Key Authentication" below.

Safety policy in one line: if a generated answer trips the PHI/cross-
patient safety check, main.py regenerates it ONCE with a stricter prompt;
if it's still unsafe, the response is blocked entirely (see the
"Retry-Then-Block Policy" section inside process_clinical_query below).
"""

from fastapi import FastAPI, HTTPException, Request, status, Security, Depends
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, Field, field_validator
from llm import generate_answer, generate_answer_strict
from retrieval import get_hybrid_context
from evaluation import (
    detect_hallucination_flags,
    score_sample_groundedness,
    run_safety_eval,
    build_system_eval,
)
from typing import Dict, Any, Optional
import re
import time
import uuid
import logging
import os
from collections import defaultdict

# ── Structured Logging Setup ───────────────────────────────────────────────────
# Replaces silent except blocks. Every failure is now traceable.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("clinical-rag")

# ── API Key Authentication ─────────────────────────────────────────────────────
# Reads the valid key from an environment variable — never hardcoded.
# Set it before starting the server:  export CLINICAL_RAG_API_KEY="your-secret"
# All clinical endpoints require this key in the X-API-Key header.
# /health is intentionally left open (monitoring tools don't need auth).

_API_KEY_NAME   = "X-API-Key"
_API_KEY_HEADER = APIKeyHeader(name=_API_KEY_NAME, auto_error=False)
_VALID_API_KEY  = os.environ.get("CLINICAL_RAG_API_KEY", "dev-key-change-in-prod")

# ── Safety Retry-Then-Block Policy ─────────────────────────────────────────────
# If a safety violation (PHI leak / cross-patient leak) is detected:
#   1. Regenerate ONCE with a stricter prompt (generate_answer_strict).
#   2. Re-run the safety check on the regenerated answer.
#   3. If still flagged → BLOCK the response entirely, return this generic message.
# Full violation details are always logged internally regardless of outcome.
BLOCKED_SAFETY_MESSAGE = (
    "This response could not be safely generated and has been withheld. "
    "Please rephrase your question or contact support if this persists."
)

async def require_api_key(api_key: str = Security(_API_KEY_HEADER)):
    """FastAPI dependency — inject into any endpoint to protect it."""
    if api_key != _VALID_API_KEY:
        logger.warning(f"Rejected request: invalid or missing API key.")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={"error": "Forbidden", "message": "Invalid or missing API key."}
        )
    return api_key


# ── Per-IP Rate Limiter ────────────────────────────────────────────────────────
# Limits each IP to RATE_LIMIT_MAX_REQUESTS per RATE_LIMIT_WINDOW_SECONDS.
# Prevents a single client from flooding Phi-3 (which runs on local CPU/GPU).
# For multi-worker deployments: replace with Redis-backed sliding window.

RATE_LIMIT_MAX_REQUESTS = 10    # max requests per window per IP
RATE_LIMIT_WINDOW_S     = 60    # window size in seconds

_rate_limit_store: Dict[str, Any] = defaultdict(lambda: {"count": 0, "window_start": 0.0})

async def check_rate_limit(request: Request):
    """FastAPI dependency — inject into any endpoint to enforce rate limiting."""
    client_ip   = request.client.host
    now         = time.time()
    record      = _rate_limit_store[client_ip]

    # Reset window if it has expired
    if now - record["window_start"] > RATE_LIMIT_WINDOW_S:
        record["count"]         = 0
        record["window_start"]  = now

    record["count"] += 1

    if record["count"] > RATE_LIMIT_MAX_REQUESTS:
        retry_after = int(RATE_LIMIT_WINDOW_S - (now - record["window_start"]))
        logger.warning(f"Rate limit exceeded for IP: {client_ip}")
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={
                "error":        "Rate_Limit_Exceeded",
                "message":      f"Too many requests. Limit: {RATE_LIMIT_MAX_REQUESTS} per {RATE_LIMIT_WINDOW_S}s.",
                "retry_after_s": retry_after,
            }
        )


# ── In-Memory Metrics Store ────────────────────────────────────────────────────
# Lightweight telemetry — no external dependency needed.
# For production scale: swap with Prometheus or a time-series DB.
_metrics: Dict[str, Any] = {
    "total_queries": 0,
    "successful_queries": 0,
    "failed_queries": 0,
    "latency_ms_total": 0.0,
    "confidence_distribution": defaultdict(int),   # {"High": N, "Medium": N, "Low": N}
    "error_counts": defaultdict(int),              # {"404": N, "500": N, ...}
}

# ── FastAPI Application ────────────────────────────────────────────────────────
app = FastAPI(
    title="Clinical RAG Assistant API",
    description=(
        "A secure API for querying clinical patient records using "
        "Hybrid Retrieval-Augmented Generation (semantic + SQL)."
    ),
    version="1.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── Request / Response Schemas ─────────────────────────────────────────────────

class QueryRequest(BaseModel):
    """
    Defines the structured format for incoming clinical questions.
    Uses Pydantic to ensure data integrity before any processing begins.
    """
    mrd_number: str = Field(..., description="The patient's unique Medical Record Number.")
    query: str = Field(..., description="The clinical question related to the patient's records.")

    @field_validator("query")
    @classmethod
    def query_must_not_be_empty(cls, v: str) -> str:
        """Ensure that the query string is not empty or whitespace."""
        if not v.strip():
            raise ValueError("The clinical query cannot be empty.")
        return v


class QueryResponse(BaseModel):
    """
    [UPGRADED] Richer response schema.
    Adds request_id for traceability, latency_ms for benchmarking,
    retrieval_source to expose which retrieval path was used, and
    safety_flagged to surface live PHI/cross-patient leak or hallucination
    checks. Full faithfulness/relevance scores live in offline eval reports
    (eval_runner.py) — not in this live response, to keep latency low.
    """
    request_id: str = Field(..., description="Unique ID for this request (use for debugging/logging).")
    mrd_number: str
    answer: str
    confidence: str = Field(..., description="LLM self-assessed confidence: High | Medium | Low")
    retrieval_source: str = Field(..., description="Which retrieval path was used: 'vector', 'sql', or 'hybrid'.")
    latency_ms: float = Field(..., description="End-to-end processing time in milliseconds.")
    safety_flagged: bool = Field(..., description="True if PHI leak, cross-patient leak, or hallucination flag fired.")
    safety_details: Dict[str, Any] = Field(default_factory=dict, description="Breakdown of which safety check(s) fired, if any.")


# ── Helper: Parse LLM Response ─────────────────────────────────────────────────

def parse_llm_response(raw_text: str) -> Dict[str, str]:
    """
    Parses the LLM's string output into a structured dictionary.
    Uses a lookahead regex to ensure 'answer' doesn't include the 'confidence' label.
    """
    answer_match = re.search(
        r"Answer:\s*(.*?)(?=\s*Confidence:|$)", raw_text, re.IGNORECASE | re.DOTALL
    )
    confidence_match = re.search(r"Confidence:\s*(High|Medium|Low)", raw_text, re.IGNORECASE)

    if answer_match:
        answer = answer_match.group(1).strip()
    else:
        answer = re.sub(r"Confidence:.*", "", raw_text, flags=re.IGNORECASE | re.DOTALL).strip()
        answer = re.sub(r"Answer:\s*", "", answer, flags=re.IGNORECASE).strip()

    confidence = confidence_match.group(1).strip() if confidence_match else "Low"
    return {"answer": answer, "confidence": confidence}


# ── Helper: Detect Retrieval Source ───────────────────────────────────────────
# [UPGRADE] Makes the retrieval path visible in every response.
# Useful for debugging and for evaluating which retrieval path performs best.

def detect_retrieval_source(context: Any) -> str:
    """
    Infers which retrieval strategy was used based on the context object.
    Extend this logic as your retrieval layer evolves.
    """
    if isinstance(context, dict):
        has_vector = bool(context.get("semantic_chunks") or context.get("vector_results"))
        has_sql    = bool(context.get("sql_results") or context.get("structured_data"))
        if has_vector and has_sql:
            return "hybrid"
        if has_sql:
            return "sql"
        if has_vector:
            return "vector"
    return "hybrid"   # default assumption for your architecture


# ── Core Endpoint ──────────────────────────────────────────────────────────────

@app.post(
    "/query",
    response_model=QueryResponse,
    status_code=status.HTTP_200_OK,
    summary="Submit a clinical query",
    tags=["Clinical RAG"],
    dependencies=[Depends(require_api_key), Depends(check_rate_limit)],
)
async def process_clinical_query(request: QueryRequest, http_request: Request):
    """
    Process a clinical query using the hybrid RAG pipeline.

    Workflow:
      1. Retrieve relevant patient context (semantic + SQL hybrid retrieval).
      2. Generate an answer via the local Phi-3 LLM.
      3. Return a structured response with answer, confidence, latency, and source.

    Error Handling:
      - 404: MRD number not found in records.
      - 400: Retrieval failure (unsupported query type or doc mismatch).
      - 500: LLM timeout or internal system failure.
    """
    # [UPGRADE] Per-request traceability: unique ID injected at the boundary.
    request_id = str(uuid.uuid4())
    start_time = time.perf_counter()

    _metrics["total_queries"] += 1
    logger.info(f"[{request_id}] Incoming query | MRD: {request.mrd_number} | Query: {request.query[:80]!r}")

    # ── Step 1: Hybrid Retrieval ───────────────────────────────────────────────
    context, error_msg = get_hybrid_context(request.mrd_number, request.query)

    if error_msg:
        _metrics["failed_queries"] += 1
        logger.warning(f"[{request_id}] Retrieval error: {error_msg}")

        if "not found" in error_msg.lower():
            _metrics["error_counts"]["404"] += 1
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={"error": "Invalid_MRD", "message": error_msg, "request_id": request_id},
            )
        _metrics["error_counts"]["400"] += 1
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": "Retrieval_Failure", "message": error_msg, "request_id": request_id},
        )

    retrieval_source = detect_retrieval_source(context)

    # ── Step 2: LLM Generation ─────────────────────────────────────────────────
    # context is now a dict — extract the text portion for the LLM.
    # Eval scores and latency live in context["eval"] and context["latency"].
    llm_context = context.get("formatted_context", str(context)) if isinstance(context, dict) else context

    try:
        raw_result = generate_answer(request.query, llm_context)
        parsed_data = parse_llm_response(raw_result)

    except Exception as e:
        _metrics["failed_queries"] += 1
        _metrics["error_counts"]["500"] += 1
        # [UPGRADE] Log the actual exception — not swallowed silently anymore.
        logger.error(f"[{request_id}] LLM generation failed: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "LLM_Failure",
                "message": "The local Phi-3 model failed to respond. Check model load and memory.",
                "request_id": request_id,
            },
        )

    # ── Step 3: Record Metrics & Return ───────────────────────────────────────
    elapsed_ms = round((time.perf_counter() - start_time) * 1000, 2)

    _metrics["successful_queries"] += 1
    _metrics["latency_ms_total"] += elapsed_ms
    _metrics["confidence_distribution"][parsed_data["confidence"]] += 1

    # Pull retrieval eval scores + raw results needed for safety checks
    eval_scores       = context.get("eval", {}) if isinstance(context, dict) else {}
    retrieval_latency = context.get("latency", {}) if isinstance(context, dict) else {}
    sql_data          = context.get("sql_results", []) if isinstance(context, dict) else []
    vector_docs       = context.get("vector_results", []) if isinstance(context, dict) else []

    # ── Step 3.5: Live Safety & Quality Checks ─────────────────────────────────
    # Fast, non-LLM checks only — runs on EVERY request without adding latency
    # for the COMMON case. Only on a flagged result do we pay the cost of a
    # second LLM call (the strict regeneration below).
    safety_result = run_safety_eval(parsed_data["answer"], sql_data, request.mrd_number)
    hallucination = detect_hallucination_flags(parsed_data["answer"], llm_context)
    groundedness  = score_sample_groundedness(vector_docs, request.query)

    safety_flagged = not safety_result["is_safe"]   # hallucination alone does NOT block — only PHI/cross-patient leaks do
    safety_details = {
        "phi_leak":            safety_result["phi_leak"],
        "cross_patient_leak":  safety_result["cross_patient_leak"],
        "hallucination_check": hallucination,
        "groundedness":        groundedness,
        "regeneration_attempted": False,
        "blocked": False,
    }

    # ── Retry-Then-Block Policy ─────────────────────────────────────────────────
    if safety_flagged:
        logger.warning(
            f"[{request_id}] SAFETY VIOLATION on first attempt | "
            f"PHI: {safety_result['phi_leak']} | Cross-patient: {safety_result['cross_patient_leak']} | "
            f"Attempting strict regeneration..."
        )
        safety_details["regeneration_attempted"] = True

        # One regeneration attempt with a stricter, violation-aware prompt.
        retry_raw     = generate_answer_strict(request.query, llm_context)
        retry_parsed  = parse_llm_response(retry_raw)
        retry_safety  = run_safety_eval(retry_parsed["answer"], sql_data, request.mrd_number)

        safety_details["retry_phi_leak"]           = retry_safety["phi_leak"]
        safety_details["retry_cross_patient_leak"] = retry_safety["cross_patient_leak"]

        if retry_safety["is_safe"]:
            # Regeneration succeeded — use the safe regenerated answer.
            logger.info(f"[{request_id}] Strict regeneration RESOLVED the safety violation.")
            parsed_data    = retry_parsed
            safety_flagged = False
        else:
            # Still unsafe after retry — BLOCK the response entirely.
            logger.error(
                f"[{request_id}] SAFETY VIOLATION PERSISTED after regeneration. "
                f"Blocking response. Details: {safety_details}"
            )
            safety_details["blocked"] = True
            parsed_data = {"answer": BLOCKED_SAFETY_MESSAGE, "confidence": "N/A"}
            _metrics["error_counts"]["safety_blocked"] += 1

    if safety_flagged or safety_details["blocked"] or hallucination["flagged"]:
        # Flagged/blocked responses are logged at WARNING regardless of confidence —
        # a "High confidence" answer that leaked PHI is the worst-case failure mode.
        logger.warning(f"[{request_id}] SAFETY DETAILS | {safety_details}")

    logger.info(
        f"[{request_id}] Success | Confidence: {parsed_data['confidence']} | "
        f"Source: {retrieval_source} | Latency: {elapsed_ms}ms | "
        f"P@{eval_scores.get('k', '?')}: {eval_scores.get('precision_at_k', 'n/a')} | "
        f"MRR: {eval_scores.get('mrr', 'n/a')} | "
        f"Retrieval: {retrieval_latency.get('total_ms', 'n/a')}ms | "
        f"SafetyFlagged: {safety_flagged} | Blocked: {safety_details['blocked']}"
    )

    return QueryResponse(
        request_id=request_id,
        mrd_number=request.mrd_number,
        answer=parsed_data["answer"],
        confidence=parsed_data["confidence"],
        retrieval_source=retrieval_source,
        latency_ms=elapsed_ms,
        safety_flagged=safety_details["blocked"],   # surfaced to caller only if ultimately blocked
        safety_details=safety_details if (safety_details["blocked"] or hallucination["flagged"]) else {},
    )


# ── /health Endpoint ───────────────────────────────────────────────────────────
# [UPGRADE] Multi-component health probe instead of a static string.
# Each component reports its own status — useful for Kubernetes liveness probes
# and deployment readiness checks.

@app.get("/health", summary="System health check", tags=["Observability"])
def health_check():
    """
    Multi-component health check.

    Probes:
      - API server status
      - LLM (Phi-3) availability (checks if model is loaded)
      - Retrieval subsystem (vector store + SQL)

    Returns overall status: 'healthy' | 'degraded' | 'unhealthy'
    """
    components: Dict[str, str] = {}

    # ── LLM probe ─────────────────────────────────────────────────────────────
    try:
        # Non-destructive: just verify the function is importable and callable.
        assert callable(generate_answer)
        components["llm"] = "healthy"
    except Exception as e:
        logger.error(f"[health] LLM probe failed: {e}")
        components["llm"] = "unhealthy"

    # ── Retrieval probe ────────────────────────────────────────────────────────
    try:
        assert callable(get_hybrid_context)
        components["retrieval"] = "healthy"
    except Exception as e:
        logger.error(f"[health] Retrieval probe failed: {e}")
        components["retrieval"] = "unhealthy"

    # ── Overall status ─────────────────────────────────────────────────────────
    if all(v == "healthy" for v in components.values()):
        overall = "healthy"
    elif any(v == "unhealthy" for v in components.values()):
        overall = "degraded"
    else:
        overall = "unhealthy"

    return {
        "status": overall,
        "model": "Phi-3-mini-4k-instruct (local)",
        "retrieval_mode": "hybrid (semantic + SQL)",
        "components": components,
    }


# ── /metrics Endpoint ──────────────────────────────────────────────────────────
# [NEW] Live telemetry surface — no Prometheus required for dev/review.
# Shows exactly what reviewers want to see: throughput, latency, error rates.

@app.get("/metrics", summary="Runtime performance metrics", tags=["Observability"],
         dependencies=[Depends(require_api_key)])
def get_metrics():
    """
    Exposes live runtime metrics for this session.

    Metrics:
      - total_queries: All queries received since startup.
      - successful_queries: Queries that returned a valid answer.
      - failed_queries: Queries that resulted in an error.
      - avg_latency_ms: Mean end-to-end latency across all successful queries.
      - confidence_distribution: Breakdown of High / Medium / Low confidence answers.
      - error_counts: HTTP error code breakdown (404, 400, 500).

    Note: Metrics reset on server restart. For persistence, integrate with
    Prometheus + Grafana or write to your SQL store via database.py.
    """
    successful = _metrics["successful_queries"]
    avg_latency = (
        round(_metrics["latency_ms_total"] / successful, 2) if successful > 0 else 0.0
    )

    return {
        "total_queries": _metrics["total_queries"],
        "successful_queries": successful,
        "failed_queries": _metrics["failed_queries"],
        "success_rate_pct": (
            round((successful / _metrics["total_queries"]) * 100, 1)
            if _metrics["total_queries"] > 0 else 0.0
        ),
        "avg_latency_ms": avg_latency,
        "confidence_distribution": dict(_metrics["confidence_distribution"]),
        "error_counts": dict(_metrics["error_counts"]),
    }


# ── Local Entry Point ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")